"""
Loan-ready business statement PDF generator.
Uses fpdf2 (version 2.8+).
"""
from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from typing import Optional

from fpdf import FPDF

# ── Colour palette ────────────────────────────────────────────────────────────
BRAND   = (26,  86, 219)   # #1a56db — CreditVoice blue
DARK    = (12,  31,  74)   # #0c1f4a — sidebar navy
WHITE   = (255, 255, 255)
LIGHT   = (240, 244, 251)  # --bg
LINE    = (229, 231, 235)  # --line
INK     = (17,  24,  39)   # --ink
MUTED   = (107, 114, 128)  # --muted
GREEN   = (6,   95,  70)
AMBER   = (120,  53,  15)
ROSE    = (136,  19,  55)

M   = 15          # left/right margin
ROW = 6.5         # standard row height
TH  = 7           # table header height


def _fmt(amount: int | float) -> str:
    """Format an integer amount as NGN 1,234,500"""
    return f"NGN {int(amount):,}"


def _short_date(dt) -> str:
    if not dt:
        return "-"
    try:
        if hasattr(dt, "strftime"):
            return dt.strftime("%d %b %Y")
        return str(dt)[:10]
    except Exception:
        return "-"


class StatementPDF(FPDF):

    def header(self):
        pass  # custom header per page handled manually

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(
            0, 5,
            "Generated by CreditVoice  |  Data reflects recorded transactions only",
            align="C",
        )
        self.ln(4)
        self.set_text_color(*MUTED)
        self.cell(0, 5, f"Page {self.page_no()}", align="C")


def _header_block(pdf: StatementPDF, owner: dict, period_label: str, ref: str):
    """Dark top banner with business name + statement meta."""
    page_w = pdf.w - 2 * M

    # Background banner
    pdf.set_fill_color(*DARK)
    pdf.rect(M, 12, page_w, 34, style="F")

    # Left: business name + phone
    pdf.set_xy(M + 4, 15)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*WHITE)
    pdf.cell(page_w * 0.55, 7, owner.get("name", "Business"), align="L")

    pdf.set_xy(M + 4, 22)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(200, 215, 240)
    biz_type = owner.get("business_type_label") or owner.get("business_category", "")
    phone    = owner.get("phone", "")
    sub_line = f"{phone}"
    if biz_type:
        sub_line += f"  |  {biz_type}"
    pdf.cell(page_w * 0.55, 5, sub_line, align="L")

    pdf.set_xy(M + 4, 29)
    pdf.set_font("Helvetica", "I", 8.5)
    pdf.set_text_color(160, 190, 230)
    pdf.cell(page_w * 0.55, 5, "Powered by CreditVoice", align="L")

    # Right: statement meta
    right_x = M + page_w * 0.57
    pdf.set_xy(right_x, 14)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*WHITE)
    pdf.cell(page_w * 0.43, 5, "BUSINESS FINANCIAL STATEMENT", align="R")

    now_str = datetime.now(timezone.utc).strftime("%d %b %Y")
    pdf.set_xy(right_x, 20)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(200, 215, 240)
    pdf.cell(page_w * 0.43, 5, f"Generated: {now_str}", align="R")

    pdf.set_xy(right_x, 26)
    pdf.cell(page_w * 0.43, 5, f"Period: {period_label}", align="R")

    pdf.set_xy(right_x, 32)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 190, 230)
    pdf.cell(page_w * 0.43, 5, f"Ref: {ref}", align="R")

    pdf.set_text_color(*INK)
    pdf.ln(1)
    pdf.set_y(50)


def _section_title(pdf: StatementPDF, title: str):
    """A coloured section header bar."""
    pdf.set_fill_color(*BRAND)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_x(M)
    pdf.cell(pdf.w - 2 * M, 7, f"  {title}", align="L", fill=True)
    pdf.ln(1)
    pdf.set_text_color(*INK)


def _kv_row(pdf: StatementPDF, label: str, value: str, highlight: bool = False):
    w = pdf.w - 2 * M
    if highlight:
        pdf.set_fill_color(*LIGHT)
        pdf.set_font("Helvetica", "B", 9)
    else:
        pdf.set_fill_color(*WHITE)
        pdf.set_font("Helvetica", "", 9)
    pdf.set_x(M)
    pdf.cell(w * 0.6, ROW, f"  {label}", align="L", fill=True)
    pdf.cell(w * 0.4, ROW, value, align="R", fill=True)
    pdf.ln(0)
    pdf.set_x(M)
    pdf.set_draw_color(*LINE)
    pdf.set_line_width(0.2)
    pdf.line(M, pdf.get_y(), pdf.w - M, pdf.get_y())
    pdf.ln(ROW)


def _table_header(pdf: StatementPDF, cols: list[tuple[str, float, str]]):
    """cols = [(label, width_fraction, align)]"""
    w = pdf.w - 2 * M
    pdf.set_fill_color(*LIGHT)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*DARK)
    pdf.set_x(M)
    for label, frac, align in cols:
        pdf.cell(w * frac, TH, label, align=align, fill=True)
    pdf.ln(TH)
    pdf.set_text_color(*INK)


def _table_row(pdf: StatementPDF, cells: list[tuple[str, float, str]], striped: bool = False):
    w = pdf.w - 2 * M
    if striped:
        pdf.set_fill_color(248, 250, 252)
        fill = True
    else:
        fill = False
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_x(M)
    for text, frac, align in cells:
        pdf.cell(w * frac, ROW, text, align=align, fill=fill)
    pdf.ln(0)
    pdf.set_x(M)
    pdf.set_draw_color(*LINE)
    pdf.set_line_width(0.15)
    pdf.line(M, pdf.get_y(), pdf.w - M, pdf.get_y())
    pdf.ln(ROW)


def generate_loan_statement(
    owner: dict,
    summary: dict,
    transactions: list[dict],
    debtors: list[dict],
    stock_items: list[dict],
    period_label: str,
    period: Optional[str] = None,
) -> bytes:
    """
    Build and return a loan-ready statement PDF as bytes.

    owner: {name, phone, business_type_label, business_category}
    summary: {total_sales_amount, total_pay_amount, total_outstanding,
              total_customers, new_customers, total_transactions,
              credit_sales_amount, direct_sales_amount}
    transactions: [{type, customer, amount, created_at, product}]
    debtors: [{name, balance, due_date, overdue}]
    stock_items: [{name, unit, quantity, selling_price}]
    """
    ref = "CV-" + hashlib.sha1(
        f"{owner.get('phone')}{period_label}{datetime.now().date()}".encode()
    ).hexdigest()[:8].upper()

    pdf = StatementPDF("P", "mm", "A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(M, 12, M)
    pdf.add_page()

    # ── Page 1: header + summary ─────────────────────────────────────────────
    _header_block(pdf, owner, period_label, ref)

    # ── Business Summary ─────────────────────────────────────────────────────
    _section_title(pdf, "BUSINESS SUMMARY")
    pdf.ln(1)
    _kv_row(pdf, "Total Revenue (Sales)",        _fmt(summary.get("total_sales_amount", 0)))
    _kv_row(pdf, "  of which  Credit Sales",     _fmt(summary.get("credit_sales_amount", 0)))
    _kv_row(pdf, "  of which  Direct / Cash Sales", _fmt(summary.get("direct_sales_amount", 0)))
    _kv_row(pdf, "Payments Received from Customers", _fmt(summary.get("total_pay_amount", 0)))
    _kv_row(pdf, "Total Outstanding Receivables", _fmt(summary.get("total_outstanding", 0)), highlight=True)
    _kv_row(pdf, "Total Customers",              f"{summary.get('total_customers', 0):,}")
    _kv_row(pdf, "New Customers (period)",       f"{summary.get('new_customers', 0):,}")
    _kv_row(pdf, "Total Transactions",           f"{summary.get('total_transactions', 0):,}")
    pdf.ln(4)

    # ── Stock Assets ─────────────────────────────────────────────────────────
    if stock_items:
        _section_title(pdf, "INVENTORY / STOCK ASSETS")
        pdf.ln(1)
        cols = [
            ("Product / Item",  0.44, "L"),
            ("Unit",            0.12, "C"),
            ("Qty in Stock",    0.20, "R"),
            ("Est. Value (NGN)",0.24, "R"),
        ]
        _table_header(pdf, cols)
        total_stock_value = 0
        for i, item in enumerate(stock_items[:40]):
            qty   = item.get("quantity") or 0
            price = item.get("selling_price") or 0
            val   = qty * price
            total_stock_value += val
            _table_row(pdf, [
                (f"  {(item.get('name') or '').title()}", 0.44, "L"),
                (item.get("unit") or "-",                 0.12, "C"),
                (f"{qty:,}",                               0.20, "R"),
                (f"{val:,.0f}" if val else "-",           0.24, "R"),
            ], striped=(i % 2 == 1))
        # Total row
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(*LIGHT)
        w = pdf.w - 2 * M
        pdf.set_x(M)
        pdf.cell(w * 0.76, ROW, "  TOTAL STOCK VALUE", align="L", fill=True)
        pdf.cell(w * 0.24, ROW, f"{total_stock_value:,.0f}", align="R", fill=True)
        pdf.ln(ROW)
        pdf.ln(4)

    # ── Outstanding Receivables ───────────────────────────────────────────────
    if debtors:
        _section_title(pdf, "OUTSTANDING RECEIVABLES")
        pdf.ln(1)
        cols = [
            ("Customer Name",   0.38, "L"),
            ("Amount Owed",     0.24, "R"),
            ("Due Date",        0.20, "C"),
            ("Status",          0.18, "C"),
        ]
        _table_header(pdf, cols)
        for i, d in enumerate(debtors[:60]):
            status = "OVERDUE" if d.get("overdue") else "Active"
            _table_row(pdf, [
                (f"  {d.get('name', '')}", 0.38, "L"),
                (f"{d.get('balance', 0):,.0f}", 0.24, "R"),
                (_short_date(d.get("due_date")),  0.20, "C"),
                (status,                          0.18, "C"),
            ], striped=(i % 2 == 1))
        pdf.ln(4)

    # ── Transaction History ───────────────────────────────────────────────────
    TYPE_LABEL = {
        "BUY":    "Credit Sale",
        "PAY":    "Payment",
        "SALE":   "Cash Sale",
        "SUPPLY": "Stock Purchase",
        "VOID":   "Voided",
    }
    if transactions:
        _section_title(pdf, f"TRANSACTION HISTORY  (last {min(len(transactions), 100)} records)")
        pdf.ln(1)
        cols = [
            ("Date",       0.17, "C"),
            ("Type",       0.18, "L"),
            ("Customer / Detail", 0.39, "L"),
            ("Amount",     0.26, "R"),
        ]
        _table_header(pdf, cols)
        for i, tx in enumerate(transactions[:100]):
            tx_type  = tx.get("type", "")
            label    = TYPE_LABEL.get(tx_type, tx_type)
            customer = tx.get("customer") or tx.get("product") or "-"
            _table_row(pdf, [
                (_short_date(tx.get("created_at")),  0.17, "C"),
                (label,                               0.18, "L"),
                (f"  {customer[:35]}",               0.39, "L"),
                (f"{tx.get('amount', 0):,.0f}",      0.26, "R"),
            ], striped=(i % 2 == 1))
        pdf.ln(4)

    # ── Disclaimer ───────────────────────────────────────────────────────────
    pdf.set_fill_color(*LIGHT)
    pdf.set_x(M)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(*MUTED)
    pdf.multi_cell(
        pdf.w - 2 * M, 4.5,
        "DISCLAIMER: This statement was generated by the CreditVoice business management "
        "platform based on transactions recorded by the business owner or their staff. "
        "CreditVoice does not audit, verify, or guarantee the accuracy of the underlying "
        "data. This document is provided for informational purposes to support access to "
        "financial services and does not constitute a certified financial statement.",
        fill=True,
        align="J",
    )

    return bytes(pdf.output())
