const LABELS = {
  school: {
    customer: "Student",
    customers: "Students",
    addCustomer: "Add Student",
    customerName: "Student name",
    customerPlaceholder: "e.g. Emeka Okafor",
    noCustomers: "No students yet. Add your first student.",
    topDebtors: "Fee defaulters",
    totalCustomers: "Total students",
    reminders: "Fee reminders",
    stock: "Textbooks & stock",
    navCustomers: "My students",
    directSale: "Direct payment",
    examples: [
      { label: "Fee payment",  text: "Ade paid school fees 15000" },
      { label: "Part payment", text: "Emeka paid tuition 8000 balance due 30/06/2026" },
      { label: "Textbooks",    text: "JSS2 textbooks 4 at 2500" },
      { label: "Clear balance",text: "Ngozi cleared school fees balance 12000" },
    ],
  },
  thrift: {
    customer: "Participant",
    customers: "Participants",
    addCustomer: "Add Participant",
    customerName: "Participant name",
    customerPlaceholder: "e.g. Amina Sule",
    noCustomers: "No participants yet. Add your first participant.",
    topDebtors: "Missed contributions",
    totalCustomers: "Total participants",
    reminders: "Contribution reminders",
    stock: "Add stock",
    navCustomers: "My participants",
    directSale: "Direct",
    examples: [
      { label: "Contribution", text: "Amina contributed 5000" },
      { label: "Part payment", text: "Tunde contributed 10000 paid 5000" },
      { label: "Catch-up",     text: "Bola contributed 8000 for last month" },
      { label: "Clear balance",text: "Oga Chidi cleared balance 15000" },
    ],
  },
  service: {
    customer: "Customer",
    customers: "Customers",
    addCustomer: "Add Customer",
    customerName: "Customer name",
    customerPlaceholder: "e.g. Mr Bayo",
    noCustomers: "No customers yet. Add your first customer.",
    topDebtors: "Outstanding balances",
    totalCustomers: "Total customers",
    reminders: "Reminders",
    stock: "Price list",
    navCustomers: "My customers",
    directSale: "Direct job",
    examples: [
      { label: "Job + deposit", text: "Bayo job 15000 paid 8000" },
      { label: "Job only",      text: "Mr Chidi repair 12000" },
      { label: "Payment",       text: "Ade paid balance 7000" },
      { label: "Direct job",    text: "I received 5000 for repair work" },
    ],
  },
  fee: {
    customer: "Customer",
    customers: "Customers",
    addCustomer: "Add Customer",
    customerName: "Customer name",
    customerPlaceholder: "e.g. Amaka Obi",
    noCustomers: "No customers yet. Add your first customer.",
    topDebtors: "Outstanding balances",
    totalCustomers: "Total customers",
    reminders: "Reminders",
    stock: "Add stock",
    navCustomers: "My customers",
    directSale: "Direct payment",
    examples: [
      { label: "Fee payment",  text: "Amina paid dues 5000" },
      { label: "Part payment", text: "Tunde paid levy 8000 balance 4000" },
      { label: "Payment",      text: "Ade paid 7000 balance due 30/06/2026" },
      { label: "Direct",       text: "I received 3000 levy payment" },
    ],
  },
};

const DEFAULT_LABELS = {
  customer: "Customer",
  customers: "Customers",
  addCustomer: "Add Customer",
  customerName: "Customer name",
  customerPlaceholder: "e.g. Amaka Obi",
  noCustomers: "No customers yet. Add your first customer.",
  topDebtors: "Top debtors",
  totalCustomers: "Total customers",
  reminders: "Reminders",
  stock: "Add stock",
  navCustomers: "My customers",
  directSale: "Direct sale",
  examples: [
    { label: "Credit + payment", text: "Amina bought rice 12000 paid 5000 due 20/06/2026" },
    { label: "Credit only",      text: "Tunde bought cement 15 bags at 800" },
    { label: "Payment",          text: "Amina paid 5000" },
    { label: "Direct sale",      text: "I sold phone 45000" },
  ],
};

export function getBizLabels(menuGroup) {
  return LABELS[menuGroup] || DEFAULT_LABELS;
}
