const LABELS = {
  school: {
    customer: "Student",
    customers: "Students",
    addCustomer: "Add Student",
    customerName: "Student name",
    customerPlaceholder: "e.g. Emeka Okafor",
    noCustomers: "No students yet. Add your first student.",
    topDebtors: "Fee defaulters",
    totalCustomers: "Total students",
    newCustomers: "New students",
    paidCustomers: "Students who paid",
    reminders: "Fee reminders",
    stock: "Textbooks & stock",
    navCustomers: "My students",
    directSale: "Direct payment",
    creditSales: "Fees invoiced",
    directSales: "Direct income",
    totalSales: "Total fees",
    outstanding: "Unpaid fees",
    payments: "Fees received",
    examples: [
      { label: "Fee payment",  text: "Ade paid school fees 15000" },
      { label: "Part payment", text: "Emeka paid tuition 8000 balance due 30/06/2026" },
      { label: "Textbooks",    text: "JSS2 textbooks 4 at 2500" },
      { label: "Clear balance",text: "Ngozi cleared school fees balance 12000" },
    ],
  },
  thrift: {
    customer: "Member",
    customers: "Members",
    addCustomer: "Add Member",
    customerName: "Member name",
    customerPlaceholder: "e.g. Amina Sule",
    noCustomers: "No members yet. Add your first member.",
    topDebtors: "Missed contributions",
    totalCustomers: "Total members",
    newCustomers: "New members",
    paidCustomers: "Members who contributed",
    reminders: "Contribution reminders",
    stock: "Add stock",
    navCustomers: "My members",
    directSale: "Direct contribution",
    creditSales: "Contributions owed",
    directSales: "Direct contributions",
    totalSales: "Total contributions",
    outstanding: "Missed contributions",
    payments: "Contributions received",
    examples: [
      { label: "Contribution", text: "Amina contributed 5000" },
      { label: "Part payment", text: "Tunde contributed 10000 paid 5000" },
      { label: "Catch-up",     text: "Bola contributed 8000 for last month" },
      { label: "Clear balance",text: "Oga Chidi cleared balance 15000" },
    ],
  },
  service: {
    customer: "Client",
    customers: "Clients",
    addCustomer: "Add Client",
    customerName: "Client name",
    customerPlaceholder: "e.g. Mr Bayo",
    noCustomers: "No clients yet. Add your first client.",
    topDebtors: "Outstanding balances",
    totalCustomers: "Total clients",
    newCustomers: "New clients",
    paidCustomers: "Clients who paid",
    reminders: "Reminders",
    stock: "Price list",
    navCustomers: "My clients",
    directSale: "Direct job",
    creditSales: "Jobs on credit",
    directSales: "Cash jobs",
    totalSales: "Total income",
    outstanding: "Outstanding balance",
    payments: "Payments received",
    examples: [
      { label: "Job + deposit", text: "Bayo job 15000 paid 8000" },
      { label: "Job only",      text: "Mr Chidi repair 12000" },
      { label: "Payment",       text: "Ade paid balance 7000" },
      { label: "Direct job",    text: "I received 5000 for repair work" },
    ],
  },
  clinic: {
    customer: "Patient",
    customers: "Patients",
    addCustomer: "Add Patient",
    customerName: "Patient name",
    customerPlaceholder: "e.g. Emeka Okafor",
    noCustomers: "No patients yet. Add your first patient.",
    topDebtors: "Outstanding bills",
    totalCustomers: "Total patients",
    newCustomers: "New patients",
    paidCustomers: "Patients who paid",
    reminders: "Payment reminders",
    stock: "Medications & supplies",
    navCustomers: "My patients",
    directSale: "Cash consultation",
    creditSales: "Consultations on credit",
    directSales: "Cash income",
    totalSales: "Total income",
    outstanding: "Outstanding balance",
    payments: "Payments received",
    examples: [
      { label: "Consultation",  text: "Emeka consultation 5000" },
      { label: "Part payment",  text: "Ngozi checkup 8000 paid 3000 balance due Friday" },
      { label: "Payment",       text: "Ade paid balance 5000" },
      { label: "Direct income", text: "I received 2000 for dressing" },
    ],
  },
  food: {
    customer: "Customer",
    customers: "Customers",
    addCustomer: "Add Customer",
    customerName: "Customer name",
    customerPlaceholder: "e.g. Amaka Obi",
    noCustomers: "No customers yet. Add your first customer.",
    topDebtors: "Outstanding tabs",
    totalCustomers: "Total customers",
    newCustomers: "New customers",
    paidCustomers: "Customers who paid",
    reminders: "Payment reminders",
    stock: "Ingredients & supplies",
    navCustomers: "My customers",
    directSale: "Cash order",
    creditSales: "Orders on credit",
    directSales: "Cash orders",
    totalSales: "Total sales",
    outstanding: "Outstanding balance",
    payments: "Payments received",
    examples: [
      { label: "Order + credit",text: "Ade ordered jollof rice 3000 paid 1500" },
      { label: "Cash order",    text: "I sold 2 plates rice 2000" },
      { label: "Payment",       text: "Tunde paid tab balance 1500" },
      { label: "Catering",      text: "Event catering 50000 paid deposit 20000" },
    ],
  },
  fee: {
    customer: "Member",
    customers: "Members",
    addCustomer: "Add Member",
    customerName: "Member name",
    customerPlaceholder: "e.g. Amaka Obi",
    noCustomers: "No members yet. Add your first member.",
    topDebtors: "Outstanding dues",
    totalCustomers: "Total members",
    newCustomers: "New members",
    paidCustomers: "Members who paid",
    reminders: "Reminders",
    stock: "Add stock",
    navCustomers: "My members",
    directSale: "Direct payment",
    creditSales: "Fees owed",
    directSales: "Direct payments",
    totalSales: "Total collected",
    outstanding: "Outstanding dues",
    payments: "Payments received",
    examples: [
      { label: "Fee payment",  text: "Amina paid dues 5000" },
      { label: "Part payment", text: "Tunde paid levy 8000 balance 4000" },
      { label: "Payment",      text: "Ade paid 7000 balance due 30/06/2026" },
      { label: "Direct",       text: "I received 3000 levy payment" },
    ],
  },
};

const DEFAULT_LABELS = {
  customer: "Customer",
  customers: "Customers",
  addCustomer: "Add Customer",
  customerName: "Customer name",
  customerPlaceholder: "e.g. Amaka Obi",
  noCustomers: "No customers yet. Add your first customer.",
  topDebtors: "Top debtors",
  totalCustomers: "Total customers",
  reminders: "Reminders",
  stock: "Add stock",
  navCustomers: "My customers",
  directSale: "Direct sale",
  examples: [
    { label: "Credit + payment", text: "Amina bought rice 12000 paid 5000 due 20/06/2026" },
    { label: "Credit only",      text: "Tunde bought cement 15 bags at 800" },
    { label: "Payment",          text: "Amina paid 5000" },
    { label: "Direct sale",      text: "I sold phone 45000" },
  ],
};

export function getBizLabels(menuGroup) {
  return LABELS[menuGroup] || DEFAULT_LABELS;
}
